### ISSUE TITLE
get_page_uri() returns the main language slug instead of translated one

### ISSUE THREAD

**Issue by MariusStuparu** [not-only-code/qtranslate-slug#37]
I need to place a link to a specific page using WP's get_page_uri($page), but it returns the main language slug instead of the translated one. Same with qtrans_convertURL(get_page_uri($page)). The URL that is displayed is invalid (www.domain.tld/en/non-enlish-slug)

For example, I need this to get the translated slugs (now it doesnt):

<a href="<?php echo qtrans_convertURL(get_page_uri(1234)) ?>">

I'm using WP 3.5.1, qTranslate 2.5.34 and qTranslate slug 1.1

**Comment by kuchenundkakao** [comment]
Did you try using get_permalink($page) ? That should give you the correct permalink,,,

**Comment by not-only-code** [comment]
For now there is no support for this function, i will add in **get_page_uri()** in next versions.
**qtrans_convertURL()** was removed since version 1.0 because was a performance conflict function, but as @kuchenundkakao says, you can use **get_permalink()** funciton to get the complete url... and if you only want the **uri** apply some kind of replacement ( _preg_replace_, _str_replace_... )

**Comment by MariusStuparu** [comment]
Ah, get_permalink() works! Thanks alot!

**Comment by not-only-code** [comment]
Ok, then i close this issue because **get_page_uri** can not be _extended_.
