### ISSUE TITLE
Menu items become impossible to translate.

### ISSUE THREAD

**Issue by johnclause** [not-only-code/qtranslate-slug#96]
People used to enter text like this `<!--:de-->DE<!--:--><!--:en-->EN<!--:-->` in field "Navigation Label" of menu item to translate it to different languages. If -slug is active, this is no longer possible.

Applies to both mq and -x.

Let us discuss before changing anything. The solution could be is to enable Language Switching buttons in menu editor. Normally, we keep input fields untranslated or responsive to Language Switching buttons.

What was the purpose of translating that input field in menu editor?

**Comment by LC43** [comment]
On Thursday, January 15, 2015, johnclause notifications@github.com wrote:

> People used to enter text like this
> DEEN in field "Navigation Label" of
> menu item to translate it to different languages. If -slug is active, this
> is no longer possible.

I thought i fixed it, but one of our users already noticed a bad bug.

> Applies to both mq and -x.
> 
> Let us discuss before changing anything. The solution could be is to
> enable Language Switching buttons in menu editor. Normally, we keep input
> fields untranslated or responsive to Language Switching buttons.
> 
> What was the purpose of translating that input field in menu editor?

From my experience, it had been very tiring to use the menus with the
comment tags. Especially if I had 5 or 6 languages. Having to look for the
right ... when i just wanted to make a small change, it was
very error prone. Its the same rationale of your buttons in the post title:
hide the working details and make a nice user experience for the user.

I dont know who committed the code, but i liked that idea. Meanwhile, it
became broken. I tried to fixed it, but i must have done something stupid,
because it only works on a very small set of conditions.

So, test behaviour 1:
I want to have a menu with different words from the title of the links. I
do not want to see  because it makes no sense to me.

Test behaviour 2:
Link has a very long title, and having to look at the comment tags in that
small input field makes me annoyed. I copy into a text editor, make
some changes and then copy back into input. Not optimal.

Test behaviour 3
I want to change the title attributes.

What do you think?

**Comment by johnclause** [comment]
Hi Pedro, I agree, that manual editing was awful, but was working as a workaround, which is better than nothing. I think I got now menu working with Language Switching Buttons, and also fixed tags and category editings imperfections. I am testing it now. I would like to release it as quickly as possible.

I am not sure how it will affect -slug plugin, I am not that familiar with -slug yet. How would you suggest to proceed, I will release and you will test -slug then and fix whatever is needed if any? Or do you want me to give you the new version to test before -x release?

**Comment by johnclause** [comment]
trunk https://github.com/qTranslate-Team/qtranslate-x now has a version 2.9.7b available for testing

**Comment by johnclause** [comment]
Zip file can also be downloaded from WP:
https://downloads.wordpress.org/plugin/qtranslate-x.2.9.7b.zip

**Comment by johnclause** [comment]
I created a pull request: https://github.com/not-only-code/qtranslate-slug/pull/97

Pedro, I am not that familiar with -slug yet, and do not know how to test it well. It seems to me that for this particular case, simple not loading of -slug menu solution is the only thing we need to do. Do you think so?

It seems that this topic is a duplicate of https://github.com/not-only-code/qtranslate-slug/issues/92#issuecomment-70574893 Let us continue the discussion there, since there is at least one more person involved on that one. I am closing this one. If you disagree re-open it, please.
